# coding: utf-8

"""
    IIoT OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iiot_openapi.models.properties_set_resp import PropertiesSetResp

class TestPropertiesSetResp(unittest.TestCase):
    """PropertiesSetResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertiesSetResp:
        """Test PropertiesSetResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertiesSetResp`
        """
        model = PropertiesSetResp()
        if include_optional:
            return PropertiesSetResp(
                result_code = 56,
                result_desc = ''
            )
        else:
            return PropertiesSetResp(
        )
        """

    def testPropertiesSetResp(self):
        """Test PropertiesSetResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
