# coding: utf-8

"""
    IIoT OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iiot_openapi.models.delete_records_request import DeleteRecordsRequest

class TestDeleteRecordsRequest(unittest.TestCase):
    """DeleteRecordsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteRecordsRequest:
        """Test DeleteRecordsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteRecordsRequest`
        """
        model = DeleteRecordsRequest()
        if include_optional:
            return DeleteRecordsRequest(
                primary_key = [
                    ''
                    ],
                values = [
                    [
                        None
                        ]
                    ]
            )
        else:
            return DeleteRecordsRequest(
                primary_key = [
                    ''
                    ],
                values = [
                    [
                        None
                        ]
                    ],
        )
        """

    def testDeleteRecordsRequest(self):
        """Test DeleteRecordsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
