# coding: utf-8

"""
    IIoT OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iiot_openapi.models.time_series_query_request import TimeSeriesQueryRequest

class TestTimeSeriesQueryRequest(unittest.TestCase):
    """TimeSeriesQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeSeriesQueryRequest:
        """Test TimeSeriesQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeSeriesQueryRequest`
        """
        model = TimeSeriesQueryRequest()
        if include_optional:
            return TimeSeriesQueryRequest(
                property_paths = [
                    ''
                    ],
                time_span = iiot_openapi.models.time_span.TimeSpan(
                    from = 56, 
                    to = 56, ),
                limit = 56,
                marker = ''
            )
        else:
            return TimeSeriesQueryRequest(
                property_paths = [
                    ''
                    ],
                time_span = iiot_openapi.models.time_span.TimeSpan(
                    from = 56, 
                    to = 56, ),
        )
        """

    def testTimeSeriesQueryRequest(self):
        """Test TimeSeriesQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
