# coding: utf-8

"""
    IIoT OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iiot_openapi.models.create_device_resp_dto import CreateDeviceRespDTO

class TestCreateDeviceRespDTO(unittest.TestCase):
    """CreateDeviceRespDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDeviceRespDTO:
        """Test CreateDeviceRespDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDeviceRespDTO`
        """
        model = CreateDeviceRespDTO()
        if include_optional:
            return CreateDeviceRespDTO(
                device_id = '',
                device_name = '',
                device_type = '',
                auth_info = iiot_openapi.models.auth_info_dto.AuthInfoDTO(
                    secret = '', ),
                create_time = '',
                update_time = ''
            )
        else:
            return CreateDeviceRespDTO(
        )
        """

    def testCreateDeviceRespDTO(self):
        """Test CreateDeviceRespDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
