# coding: utf-8

"""
    IIoT OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iiot_openapi.models.expression_settings import ExpressionSettings

class TestExpressionSettings(unittest.TestCase):
    """ExpressionSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExpressionSettings:
        """Test ExpressionSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExpressionSettings`
        """
        model = ExpressionSettings()
        if include_optional:
            return ExpressionSettings(
                condition = '',
                expressions = [
                    iiot_openapi.models.expression.Expression(
                        name = '', 
                        condition = '', 
                        expression = '', 
                        property_path = '', )
                    ]
            )
        else:
            return ExpressionSettings(
                expressions = [
                    iiot_openapi.models.expression.Expression(
                        name = '', 
                        condition = '', 
                        expression = '', 
                        property_path = '', )
                    ],
        )
        """

    def testExpressionSettings(self):
        """Test ExpressionSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
