
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-28T02:50:50+1200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5687288eeb428a70a1db61589d3f344ed8049953",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
