IAM_TIME_SECONDS_DELAY = 3600  # 1 час
REQUEST_DEFERRED_SEARCH_START_DELAY = 300  # 5 минут
REQUEST_DEFERRED_SEARCH = 15
PAGE_RANGE = range(0, 5)

RPS_V1 = 2  # REQUESTS PER SECONDS для Yandex Search API_V1
MAX_RETRY_ATTEMPTS = RPS_V1 * 2
