
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-28T11:34:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d54d5466c9566c6a7935e86d05d26e11a46de181",
 "version": "2.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
