from setuptools import setup, find_packages

setup(
    name="solentra",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=0.24.0",
        # "torch>=1.9.0",  # Temporarily commented out for testing
        "transformers>=4.5.0",
        "requests>=2.25.0",
        "beautifulsoup4>=4.9.0",
        "arxiv>=1.0.0",
        "tweepy>=4.0.0",
        "python-dotenv>=0.19.0",
        "tqdm>=4.62.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "jupyter>=1.0.0",
        "ipython>=7.0.0",
        "pytest>=6.2.0",
        "black>=21.5b2",
        "isort>=5.9.0",
        "flake8>=3.9.0",
        "mypy>=0.910",
        "plotly>=5.0.0",
        "openai>=1.0.0",
        "GitPython>=3.1.0",
        "markdown2>=2.4.0",
        "PyPDF2>=3.0.0",
        "networkx>=2.8.0",
        "nbformat>=5.7.0",
        "PyYAML>=6.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.0",
            "black>=21.5b2",
            "isort>=5.9.0",
            "flake8>=3.9.0",
            "mypy>=0.910",
            "jupyter>=1.0.0",
            "ipython>=7.0.0",
        ]
    },
    author="Solentra",
    author_email="solentrasol@gmail.com",
    description="A powerful Python package for creating science-themed AI agents",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/solentra/solentra",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Libraries :: Application Frameworks",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Distributed Computing",
    ],
    python_requires=">=3.8",
)
