# Generated by Django 3.1.7 on 2021-04-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjelp', '0001_initial'),
    ]

    operations = [
	migrations.AlterField(
            model_name='faqsection',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='placeholder',
            field=models.CharField(max_length=255),
        ),
    ]
