TILE_HEALTH = {
    "big rock": 45,
    "blue dye": 6,
    "bluebell": 10,
    "blueprint": 8,
    "bowl": 6,
    "brick": 12,
    "campfire": 8,
    "carroot": 8,
    "carrot": 4,
    "clay": 12,
    "coal ore": 20,
    "coal": 8,
    "composter": 8,
    "corpse": 1,
    "flint axe": 6,
    "flint hammer": 10,
    "flint pickaxe": 6,
    "flint shovel": 6,
    "flint sword": 6,
    "flint": 16,
    "ice": 12,
    "junk": 1,
    "left": 1,
    "manual press": 12,
    "mushroom block": 5,
    "mushroom hut": 30,
    "mushroom shaper": 13,
    "mushroom stew": 6,
    "mushroom": 10,
    "obelisk": 1,
    "paper": 8,
    "player": 20,
    "rabbit adult": 10,
    "rabbit child": 6,
    "rabbit fur": 8,
    "rabbit hole": 1,
    "rabbit meat": 6,
    "roasted mushroom": 8,
    "roasted rabbit meat": 10,
    "rock": 20,
    "rock axe": 10,
    "rock pickaxe": 10,
    "rock shovel": 10,
    "rock sword": 10,
    "sapling": 4,
    "sawbench": 12,
    "small barrel": 10,
    "small crate": 10,
    "spore": 4,
    "stick": 4,
    "stone brick": 16,
    "stone": 16,
    "tree": 15,
    "treeling": 9,
    "up": 1,
    "water": 8,
    "wood pulp": 6,
    "wood": 4,
    "wooden bed": 12,
    "wooden cabin": 42,
    "wooden door": 1,
    "workbench": 5,
}
FLOOR_HEALTH = {
    "dirt": 5,
    "ice": 12,
    "void": 1,
    "wood floor": 6,
}