# This file was auto-generated by Fern from our API Definition.

import typing

UploadedMediaObjectResponseBodyTriggerReason = typing.Union[
    typing.Literal[
        "api", "panicButton", "periodicStill", "safetyEvent", "tripEndStill", "tripStartStill", "videoRetrieval"
    ],
    typing.Any,
]
