SIDAS_ECS_COORDINATOR_CLUSTER_ENV_KEY = "SIDAS_ECS_COORDINATOR_CLUSTER"
SIDAS_ECS_COORDINATOR_TASK_DEF_ENV_KEY = "SIDAS_ECS_COORDINATOR_TASK_DEF"
SIDAS_ECS_MATERIALIZER_CONTAINER_NAME_KEY = "SIDAS_ECS_MATERIALIZER_CONTAINER_NAME"
SIDAS_ECS_COORDINATOR_TASK_SECURITY_GROUP_ID_KEY = (
    "SIDAS_ECS_COORDINATOR_TASK_SECURITY_GROUP_ID"
)
SIDAS_ECS_COORDINATOR_TASK_SUBNET_GROUP_ID_KEY = (
    "SIDAS_ECS_COORDINATOR_TASK_SUBNET_GROUP_ID"
)
