"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moovio_sdk.types import BaseModel
from typing_extensions import TypedDict


class EnrichedIndustryTypedDict(TypedDict):
    r"""An industry's MCC/SIC/NAICS codes, along with descriptive title."""

    title: str
    naics: str
    r"""North American Industry Classification System"""
    sic: str
    r"""Standard Industrial Classification"""
    mcc: str
    r"""Merchant Category Code"""


class EnrichedIndustry(BaseModel):
    r"""An industry's MCC/SIC/NAICS codes, along with descriptive title."""

    title: str

    naics: str
    r"""North American Industry Classification System"""

    sic: str
    r"""Standard Industrial Classification"""

    mcc: str
    r"""Merchant Category Code"""
