
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-29T09:40:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c47ea1d648ff3514ff148d97091c368fcd19685",
 "version": "4.0.1a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
