
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-30T12:31:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1280990a7bede773d7a4c8cb721c876bb7bef82",
 "version": "2025.05.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
