# Generated by Django 5.1.2 on 2025-04-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='file_test',
        ),
    ]
