# Generated by Django 5.1.2 on 2025-04-25 02:22

import django_sohoui.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0006_alter_demomodel_options_alter_examplemodel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='website',
            field=django_sohoui.fields.UiURLField(blank=True, default='', null=True, verbose_name='网站'),
        ),
    ]
