# Generated by Django 5.2.1 on 2025-05-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0020_exampleitem_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampleitem',
            name='amount',
        ),
    ]
