# This file was auto-generated by Fern from our API Definition.

import typing

PostV1CategoriesRequestType = typing.Union[
    typing.Literal["ASSET", "LIABILITY", "EQUITY", "REVENUE", "EXPENSE"], typing.Any
]
