# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing
from .chat_completion_token_logprob import ChatCompletionTokenLogprobParams


class LogprobsParams(typing_extensions.TypedDict):
    content: typing.Sequence[ChatCompletionTokenLogprobParams]
    """
    A list of message content tokens with log probability information.
    """

    refusal: typing.Sequence[ChatCompletionTokenLogprobParams]
    """
    A list of message refusal tokens with log probability information.
    """
