# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetV1BanksCreateLinkResponse(UniversalBaseModel):
    link_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Plaid link token
    """

    expiration: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The expiration date and time of the link token
    """

    request_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Plaid request ID for tracking this link token creation
    """

    user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Plaid user ID associated with this link token
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
