# Generated by Django 3.2.19 on 2023-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO_user_details", "0004_userdetails_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="employee_id",
            field=models.CharField(blank=True, help_text="The user's internal employee id", max_length=255, null=True),
        ),
    ]
