"""Stub file for reflex_enterprise/__init__.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------

from . import components as components
from .app import AppEnterprise as App  # noqa: F401
from .components import mantine as mantine
from .components.ag_charts import ag_chart as ag_chart
from .components.ag_grid import ag_grid as ag_grid
from .components.ag_grid.wrapper import ModelWrapper as ModelWrapper
from .components.ag_grid.wrapper import ModelWrapperSSRM as ModelWrapperSSRM
from .components.ag_grid.wrapper import model_wrapper as model_wrapper
from .components.ag_grid.wrapper import model_wrapper_ssrm as model_wrapper_ssrm
from .components.dnd import dnd as dnd
from .components.mantine.autocomplete import autocomplete as autocomplete
from .components.mantine.collapse import collapse as collapse
from .components.mantine.combobox import combobox as combobox
from .components.mantine.dates import dates as dates
from .components.mantine.json_input import json_input as json_input
from .components.mantine.loading_overlay import loading_overlay as loading_overlay
from .components.mantine.multi_select import multi_select as multi_select
from .components.mantine.number_formatter import number_formatter as number_formatter
from .components.mantine.pill import pill as pill
from .components.mantine.pills_input import pills_input as pills_input
from .components.mantine.ring_progress import ring_progress as ring_progress
from .components.mantine.semi_circle_progress import (
    semi_circle_progress as semi_circle_progress,
)
from .components.mantine.spoiler import spoiler as spoiler
from .components.mantine.tags_input import tags_input as tags_input
from .components.mantine.timeline import timeline as timeline
from .components.mantine.tree import tree as tree
from .components.map import map as map
from .config import ConfigEnterprise as Config  # noqa: F401
from .utils import arrow_func as arrow_func
from .vars import ArgsFunctionOperationPromise as ArgsFunctionOperationPromise
from .vars import ElementAPI as ElementAPI
from .vars import JSAPIVar as JSAPIVar
from .vars import LambdaVar as LambdaVar
from .vars import LiteralLambdaVar as LiteralLambdaVar
from .vars import PassthroughAPI as PassthroughAPI
from .vars import PromiseVar as PromiseVar
from .vars import is_static as is_static
from .vars import static as static

_MANTINE_MAPPING = {
    "components.mantine.autocomplete": ["autocomplete"],
    "components.mantine.collapse": ["collapse"],
    "components.mantine.combobox": ["combobox"],
    "components.mantine.json_input": ["json_input"],
    "components.mantine.loading_overlay": ["loading_overlay"],
    "components.mantine.multi_select": ["multi_select"],
    "components.mantine.number_formatter": ["number_formatter"],
    "components.mantine.pill": ["pill"],
    "components.mantine.pills_input": ["pills_input"],
    "components.mantine.ring_progress": ["ring_progress"],
    "components.mantine.semi_circle_progress": ["semi_circle_progress"],
    "components.mantine.spoiler": ["spoiler"],
    "components.mantine.tags_input": ["tags_input"],
    "components.mantine.tree": ["tree"],
    "components.mantine.timeline": ["timeline"],
    "components.mantine.dates": ["dates"],
}
_SUBMODULES = {"components"}
_SUBMOD_ATTRS = {
    "app": [("AppEnterprise", "App")],
    "utils": ["arrow_func"],
    "config": [("ConfigEnterprise", "Config")],
    "components": ["mantine"],
    "components.ag_grid": ["ag_grid"],
    "components.ag_charts": ["ag_chart"],
    **_MANTINE_MAPPING,
    "components.ag_grid.wrapper": [
        "model_wrapper",
        "model_wrapper_ssrm",
        "ModelWrapper",
        "ModelWrapperSSRM",
    ],
    "components.dnd": ["dnd"],
    "components.map": ["map"],
    "vars": [
        "ArgsFunctionOperationPromise",
        "PassthroughAPI",
        "ElementAPI",
        "JSAPIVar",
        "LambdaVar",
        "LiteralLambdaVar",
        "PromiseVar",
        "is_static",
        "static",
    ],
}
