# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_v1reports_generate_response_income_statement_hierarchical_totals import (
    GetV1ReportsGenerateResponseIncomeStatementHierarchicalTotals,
)


class GetV1ReportsGenerateResponseIncomeStatementHierarchical(UniversalBaseModel):
    revenue: typing.Optional[typing.List[typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Hierarchical list of revenue accounts
    """

    expenses: typing.Optional[typing.List[typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Hierarchical list of expense accounts
    """

    totals: typing.Optional[GetV1ReportsGenerateResponseIncomeStatementHierarchicalTotals] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
