# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetV1ReportsGenerateResponseCashFlowStatementHierarchicalOperatingActivitiesAdjustments(UniversalBaseModel):
    depreciation: typing.Optional[float] = None
    change_in_accounts_receivable: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="changeInAccountsReceivable")
    ] = None
    change_in_inventory: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="changeInInventory")
    ] = None
    change_in_accounts_payable: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="changeInAccountsPayable")
    ] = None
    change_in_accrued_liabilities: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="changeInAccruedLiabilities")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
