# Generated by Django 4.2.10 on 2024-02-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('matrix', '0003_add_managed_by_app_label'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='matrixprofile',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='matrixroom',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rooms', to='core.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='matrixroom',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ] + [
        migrations.RunSQL(
            f"ALTER TABLE matrix_{model_name} drop column if exists site_id;"
        ) for model_name  in
        [
            "matrixprofile",
            "matrixroom",
        ]
    ]

