
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-21T15:50:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "77ac10c983eb727ff13db6b3f220d9de7e98137f",
 "version": "2.62.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
