from _typeshed import Incomplete

__version__: str
__application__: str

def get_current_time() -> str: ...

logger: Incomplete

def exception_handler(type, value, tb) -> None: ...
def get_name_from_tags(tags: list) -> str: ...
def get_tgws(client, tgw_id: str, log_level: int) -> list: ...
def get_tgw_routes(client, tgw_rt_id: str, log_level: int) -> list: ...
def get_tgw_rts(client, tgw_id: str, tgw_rt_id: str, log_level: int) -> list: ...
def get_tgw_attachments(client, tgw_id: str, tgw_attachment_id: str, log_level: int) -> list: ...
def get_cgws(client, cgw_id: str, log_level: int) -> list: ...
def get_tgw_vpn_connections(client, tgw_id: str, tgw_vpn_connection_id: str, log_level: int) -> list: ...
def login_to_aws(service: str, region: str, log_level: int): ...
def get_params(): ...
def main() -> None: ...
