# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class File(UniversalBaseModel):
    filename: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the file, used when passing the file to the model as a 
    string.
    """

    file_data: typing.Optional[str] = pydantic.Field(default=None)
    """
    The base64 encoded file data, used when passing the file to the model 
    as a string.
    """

    file_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of an uploaded file to use as input.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
