# coding: utf-8

"""
    FINBOURNE Candela Platform Web API

    FINBOURNE Technology  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic.v1 import StrictStr, Field, BaseModel, Field 
from finbourne_candela.models.max_len import MaxLen

class IArr(BaseModel):
    """
    Class representing a variable length array intent field with a defined element type.  # noqa: E501
    """
    is_nullable: Optional[Any] = None
    min_len: Optional[Any] = Field(...)
    max_len: MaxLen = Field(...)
    obj: Obj = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["is_nullable", "min_len", "max_len", "obj"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IArr:
        """Create an instance of IArr from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of max_len
        if self.max_len:
            _dict['max_len'] = self.max_len.to_dict()
        # override the default output from pydantic by calling `to_dict()` of obj
        if self.obj:
            _dict['obj'] = self.obj.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if is_nullable (nullable) is None
        # and __fields_set__ contains the field
        if self.is_nullable is None and "is_nullable" in self.__fields_set__:
            _dict['is_nullable'] = None

        # set to None if min_len (nullable) is None
        # and __fields_set__ contains the field
        if self.min_len is None and "min_len" in self.__fields_set__:
            _dict['min_len'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IArr:
        """Create an instance of IArr from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IArr.parse_obj(obj)

        _obj = IArr.parse_obj({
            "is_nullable": obj.get("is_nullable"),
            "min_len": obj.get("min_len"),
            "max_len": MaxLen.from_dict(obj.get("max_len")) if obj.get("max_len") is not None else None,
            "obj": Obj.from_dict(obj.get("obj")) if obj.get("obj") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
