
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-28T11:32:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "11be8a170e744c28c796d311b2b0ffeef6521f92",
 "version": "4.0.1a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
