# Generated by Django 5.1.2 on 2024-10-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0036_alter_event_header_image_alter_event_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesforceSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "salesforce_instance",
                    models.URLField(default="https://salesforce.com"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretalx_salesforce_settings",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
