# Generated by Django 5.1.2 on 2025-05-18 08:27

import custom_base_django.models.choices
import custom_base_django.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_base_django', '0004_alter_runperiodictasks_status_workflow_workflowstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('struct_name', models.CharField(max_length=255, verbose_name='struct_name')),
                ('extra_non_required_fields', models.JSONField(blank=True, default=list, null=True, verbose_name='extra_non_required_fields')),
                ('nested', models.JSONField(blank=True, default=dict, null=True, verbose_name='nested')),
                ('nested_fields', models.JSONField(blank=True, default=dict, null=True, verbose_name='nested_fields')),
                ('extra_writable_fields', models.JSONField(blank=True, default=list, null=True, verbose_name='extra_writable_fields')),
                ('readonly_fields', models.JSONField(blank=True, default=list, null=True, verbose_name='readonly_fields')),
                ('exclude_fields', models.JSONField(blank=True, default=list, null=True, verbose_name='exclude_fields')),
                ('extra_fields', models.JSONField(blank=True, default=list, null=True, verbose_name='extra_fields')),
                ('extra_validations', models.JSONField(blank=True, default=list, null=True, verbose_name='extra_validations')),
                ('blank_objects', models.JSONField(blank=True, default=dict, null=True, verbose_name='blank_objects')),
                ('pk_field', models.IntegerField(blank=True, null=True, verbose_name='pk')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='model')),
                ('must_save', models.BooleanField(default=True, verbose_name='must_save')),
                ('need_authentication', models.BooleanField(default=False, verbose_name='need_authentication')),
                ('custom_query', models.JSONField(blank=True, default=dict, null=True, verbose_name='custom_query')),
                ('fields', models.JSONField(blank=True, default=list, null=True, verbose_name='fields')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='workflow',
            name='transition_status',
            field=custom_base_django.models.choices.ChoiceForeignKey(blank=True, default=custom_base_django.utils.Defaults.object, limit_choices_to=models.Q(('title', 'transition_status')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_status', to='custom_base_django.choice', verbose_name='transition status'),
        ),
        migrations.AlterField(
            model_name='runperiodictasks',
            name='status',
            field=custom_base_django.models.choices.ChoiceForeignKey(blank=True, default=custom_base_django.utils.Defaults.object, limit_choices_to=models.Q(('title', 'task_status')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status', to='custom_base_django.choice', verbose_name='task_status'),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
