# Generated by Django 5.1.2 on 2025-05-19 05:40

import custom_base_django.models.choices
import custom_base_django.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_base_django', '0005_basestructure_alter_workflow_transition_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowhistory',
            old_name='last_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='workflowstate',
            old_name='form_struct',
            new_name='serializer_struct',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='content_type_wf',
        ),
        migrations.AlterField(
            model_name='runperiodictasks',
            name='status',
            field=custom_base_django.models.choices.ChoiceForeignKey(blank=True, default=custom_base_django.utils.Defaults.object, limit_choices_to=models.Q(('title', 'task_status')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status', to='custom_base_django.choice', verbose_name='task_status'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='transition_status',
            field=custom_base_django.models.choices.ChoiceForeignKey(blank=True, default=custom_base_django.utils.Defaults.object, limit_choices_to=models.Q(('title', 'transition_status')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_status', to='custom_base_django.choice', verbose_name='transition status'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='custom_base_django.workflow'),
        ),
    ]
