"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from alph_sdk.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class DeleteProjectResponseBodyTypedDict(TypedDict):
    r"""Delete Project"""

    message: NotRequired[str]
    status: NotRequired[str]


class DeleteProjectResponseBody(BaseModel):
    r"""Delete Project"""

    message: Optional[str] = None

    status: Optional[str] = None


class DeleteProjectResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: DeleteProjectResponseBodyTypedDict


class DeleteProjectResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: DeleteProjectResponseBody
