"""Stub file for reflex_enterprise/components/mantine/json_input.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from typing import Any, Dict, List, Literal, Mapping, Optional, Sequence, overload

from reflex.components.component import Component
from reflex.components.core.breakpoints import Breakpoints
from reflex.event import EventType
from reflex.vars.base import Var

from reflex_enterprise.components.mantine.base import (
    BaseMantineInput,
    MantineDescriptionProps,
    MantineErrorProps,
    MantineLabelProps,
)

class JsonInput(
    BaseMantineInput, MantineLabelProps, MantineDescriptionProps, MantineErrorProps
):
    @overload
    @classmethod
    def create(  # type: ignore
        cls,
        *children,
        autosize: Var[bool] | bool | None = None,
        default_value: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        format_on_blur: Var[bool] | bool | None = None,
        input_size: Var[str] | str | None = None,
        input_wrapper_order: List[Literal["description", "error", "input", "label"]]
        | Var[List[Literal["description", "error", "input", "label"]]]
        | None = None,
        max_rows: Var[int] | int | None = None,
        min_rows: Var[int] | int | None = None,
        pointer: Var[bool] | bool | None = None,
        placeholder: Var[str] | str | None = None,
        radius: Var[int | str] | int | str | None = None,
        required: Var[bool] | bool | None = None,
        size: Var[str] | str | None = None,
        validation_error: Component | Var[Component | str] | str | None = None,
        value: Var[str] | str | None = None,
        with_asterisk: Var[bool] | bool | None = None,
        with_error_styles: Var[bool] | bool | None = None,
        wrapper_props: Dict[str, Any] | Var[Dict[str, Any]] | None = None,
        clearable: Var[bool] | bool | None = None,
        multiline: Var[bool] | bool | None = None,
        read_only: Var[bool] | bool | None = None,
        label: Component | Var[Component | str] | str | None = None,
        label_props: Var[dict] | dict | None = None,
        description: Component | Var[Component | str] | str | None = None,
        description_props: Var[dict] | dict | None = None,
        error: Component | Var[Component | bool | str] | bool | str | None = None,
        error_props: Var[dict] | dict | None = None,
        left_section: Component | Var[Component | str] | str | None = None,
        left_section_props: Var[dict] | dict | None = None,
        left_section_width: Var[float | str] | float | str | None = None,
        left_section_pointer_events: Var[str] | str | None = None,
        right_section: Component | Var[Component | str] | str | None = None,
        right_section_props: Var[dict] | dict | None = None,
        right_section_width: Var[float | str] | float | str | None = None,
        right_section_pointer_events: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        autofocus: bool | None = None,
        custom_attrs: dict[str, Var | Any] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[()] | EventType[str]] = None,
        on_click: Optional[EventType[()]] = None,
        on_context_menu: Optional[EventType[()]] = None,
        on_double_click: Optional[EventType[()]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "JsonInput":
        """Create the Reflex Enterprise component."""
        ...

json_input = JsonInput.create
