# Generated by Django 5.1.2 on 2025-04-25 02:26

import django_sohoui.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0007_alter_examplemodel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='description',
            field=django_sohoui.fields.UiTextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
    ]
