# Generated by Django 5.1.2 on 2025-04-23 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0002_remove_examplemodel_file_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='adminmenus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sohoui.adminmenus', verbose_name='菜单'),
        ),
    ]
