# Generated by Django 5.1.2 on 2025-04-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0004_alter_examplemodel_adminmenus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demomodel',
            old_name='file_test',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='demomodel',
            name='name',
        ),
        migrations.AddField(
            model_name='demomodel',
            name='adminmenus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sohoui.adminmenus', verbose_name='菜单'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='计数'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='description',
            field=models.TextField(default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='电子邮件'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='website',
            field=models.URLField(blank=True, default='', null=True, verbose_name='网站'),
        ),
    ]
