# Generated by Django 5.1.2 on 2025-05-20 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0017_demomodelitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodelitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sohoui.demomodel', verbose_name='示例模型'),
        ),
    ]
