# Generated by Django 5.2.1 on 2025-05-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sohoui', '0018_demomodelitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModelItem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sohoui.demomodel', verbose_name='示例模型')),
            ],
        ),
    ]
