# THIS IS VERY UNSTABLE AND MIGHT BE WRONG

from typing import Protocol, TypedDict, Any

from typing_extensions import Unpack
from googleapiclient.http import HttpRequest
from googleapiclient.discovery import Resource


class Sites(Protocol):
    def add(self) -> None: ...

    def delete(self) -> None: ...

    def get(self) -> None: ...

    def list(self) -> HttpRequest: ...


class SearchAnalytics(Protocol):
    class SearchAnalyticsQueryKwargs(TypedDict):
        siteUrl: str

    def query(self, **kwargs: Unpack[SearchAnalyticsQueryKwargs]) -> HttpRequest: ...

    def close(self) -> None: ...


class GscService(Protocol):
    def close(self) -> None: ...

    def new_batch_http_request(self) -> None: ...

    def searchanalytics(self) -> SearchAnalytics: ...

    def sitemaps(self) -> None: ...

    def sites(self) -> Sites: ...

    def urlInspection(self) -> None: ...

    def urlTestingTools(self) -> None: ...
