
class DataAttributes:
    INTERACTIVE_ELEMENT = "data-mcp-interactive-element"
    DISPLAY_CONTAINER = "data-mcp-display-container"
    DISPLAY_ITEM_TEXT = "data-mcp-display-item-text"
    ELEMENT_LABEL = "data-mcp-element-label"
    ELEMENT_TYPE = "data-mcp-element-type"
    ELEMENT_STATE = "data-mcp-element-state"
    NAVIGATES_TO = "data-mcp-navigates-to"
    VALUE = "data-mcp-value"
    DISPLAY_ITEM_ID = "data-mcp-display-item-id"
    PURPOSE = "data-mcp-purpose"
    GROUP = "data-mcp-group"
    CONTROLS = "data-mcp-controls"
    UPDATES_CONTAINER = "data-mcp-updates-container"
    REGION = "data-mcp-region"
    DISABLED_STATE = "data-mcp-disabled"
    READONLY_STATE = "data-mcp-readonly"
    LOADING_INDICATOR_FOR = "data-mcp-loading-indicator-for"
    STATUS_MESSAGE_CONTAINER = "data-mcp-status-message-container"
    FIELD_NAME = "data-mcp-field"
