# Generated by Django 5.2.1 on 2025-05-19 18:56

import ardhi_framework.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentParcelRegistryModel',
            fields=[
                ('id', ardhi_framework.fields.ArdhiPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', ardhi_framework.fields.UserDetailsField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', ardhi_framework.fields.UserDetailsField()),
                ('fz', ardhi_framework.fields.FreezeStateField(default=dict, editable=False)),
                ('parcel_number', ardhi_framework.fields.ParcelNumberField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventChangeLogModel',
            fields=[
                ('id', ardhi_framework.fields.ArdhiPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', ardhi_framework.fields.UserDetailsField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', ardhi_framework.fields.UserDetailsField()),
                ('fz', ardhi_framework.fields.FreezeStateField(default=dict, editable=False)),
                ('event_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_in', ardhi_framework.fields.FreezeStateField(default=dict, editable=False)),
                ('application_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parcel_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ardhi_framework.departmentparcelregistrymodel')),
            ],
            options={
                'verbose_name': 'Change Log Activity',
                'verbose_name_plural': 'Change Logs Activity',
            },
        ),
        migrations.CreateModel(
            name='ParcelRelatedDocumentsModel',
            fields=[
                ('id', ardhi_framework.fields.ArdhiPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', ardhi_framework.fields.UserDetailsField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', ardhi_framework.fields.UserDetailsField()),
                ('fz', ardhi_framework.fields.FreezeStateField(default=dict, editable=False)),
                ('document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_data', ardhi_framework.fields.FreezeStateField(blank=True, default=dict, editable=False, null=True)),
                ('parcel_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ardhi_framework.departmentparcelregistrymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
