
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-30T09:42:48+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "479e70941cc07aa95b785158ad549ed5aca00185",
 "version": "1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
