# Generated by Django 4.2.19 on 2025-04-11 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pdf_actions", "0002_add_page_size_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportpdfsettings",
            name="rtl_support",
            field=models.BooleanField(
                default=False,
                help_text="Enable right-to-left (RTL) text support for Arabic and other RTL languages",
            ),
        ),
        migrations.AlterField(
            model_name="exportpdfsettings",
            name="items_per_page",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Number of items to display per page",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
