# This file is automatically generated by versioningit during build stage. Do not edit it manually.
# Configuration is stored in the pyproject.toml file.

version = '0.7.2'
version_tuple = (0, 7, 2)
base_version = '0.7.2'  # Latest released version known at build time
git_revision = '2b5e669'
git_revision_full = '2b5e669952a7b5ce3fc8e033ad20970b92c30b37'
git_branch = 'None'
git_revision_date = '2025-05-28T12:38:46'
build_date = '2025-05-28T13:12:33'

