# coding: utf-8

"""
    Keap REST API

    Keap REST Core Service

    The version of the OpenAPI document: 2.70.0.809589
    Contact: api@keap.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DealStatus(str, Enum):
    """
    Enum representing the status of a deal.
    """

    """
    allowed enum values
    """
    ACTIVE = 'ACTIVE'
    WON = 'WON'
    LOST = 'LOST'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DealStatus from a JSON string"""
        return cls(json.loads(json_str))

