# Generated by Django 3.1.4 on 2020-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjelp', '0002_change_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqsection',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='faqsection',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Show'),
        ),
    ]
