# Generated by Django 4.2.10 on 2024-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjelp', '0006_add_managed_by_app_label'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='faqquestion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='faqsection',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='issuecategory',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='icon',
            field=models.CharField(blank=True, choices=[], default='question_answer', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='icon',
            field=models.CharField(blank=True, choices=[], default='question_answer', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='icon',
            field=models.CharField(blank=True, choices=[], default='bug_report', max_length=50, verbose_name='Icon'),
        ),
         migrations.RemoveConstraint(
            model_name='faqsection',
            name='unique_section_name_per_site',
        ),
        migrations.RemoveConstraint(
            model_name='issuecategory',
            name='unique_category_name_per_site_without_parent',
        ),
        migrations.RemoveConstraint(
            model_name='issuecategory',
            name='unique_category_name_per_site_with_parent',
        ),
    ] + [
        migrations.RunSQL(
            f"ALTER TABLE hjelp_{model_name} drop column if exists site_id;"
        ) for model_name  in
        [
            "faqquestion",
            "faqsection",
            "issuecategory",
        ]
    ] + [
        migrations.AlterField(
            model_name='faqsection',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='issuecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None)), fields=('name',), name='unique_category_name_without_parent'),
        ),
        migrations.AddConstraint(
            model_name='issuecategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_category_name_with_parent'),
        ),
    ]

