
ADMINISTRATOR_RIGHTS: str = 'ADMINISTRATOR'
PROPRIETOR_RIGHTS: str = 'PROPRIETOR'
TENANTS_IN_COMMON_TYPE: str = 'TENANTS_IN_COMMON'
JOINT_TENANCY_TYPE: str = 'JOINT_TENANCY'
SOLE_OWNERSHIP_TYPE: str = 'SOLE_OWNERSHIP'
