"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fileupload import FileUpload, FileUploadTypedDict
from .stagefiletypeenum import StageFileTypeEnum
from flowai_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class StageCreationRequestTypedDict(TypedDict):
    r"""Schema for creating stages via SDK (compatible with JSON)"""

    files: List[FileUploadTypedDict]
    source_type: StageFileTypeEnum
    r"""Enum for stage file types that inherits from str for better JSON/OpenAPI compatibility"""
    project_id: str
    r"""UUID of the project"""


class StageCreationRequest(BaseModel):
    r"""Schema for creating stages via SDK (compatible with JSON)"""

    files: List[FileUpload]

    source_type: StageFileTypeEnum
    r"""Enum for stage file types that inherits from str for better JSON/OpenAPI compatibility"""

    project_id: str
    r"""UUID of the project"""
