"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class StageFileTypeEnum(str, Enum):
    r"""Enum for stage file types that inherits from str for better JSON/OpenAPI compatibility"""

    AGENT_RULES = "AGENT_RULES"
    TOOL_DEFINITIONS = "TOOL_DEFINITIONS"
    DATABASE_SCHEMA_RULES = "DATABASE_SCHEMA_RULES"
    CUSTOM_DATA_FILES = "CUSTOM_DATA_FILES"
    RELATIONAL_DB_SCHEMA = "RELATIONAL_DB_SCHEMA"
