"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flowai_sdk.types import BaseModel
from flowai_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetStageDetailsStagesStageIDGetRequestTypedDict(TypedDict):
    stage_id: int


class GetStageDetailsStagesStageIDGetRequest(BaseModel):
    stage_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
