
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-29T09:42:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a4364bf92e8e1d1a3ccb77de14d813c5bb40acc",
 "version": "2.0.1a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
