"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tokenbalance import TokenBalance, TokenBalanceTypedDict
from compass_api_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PortfolioTypedDict(TypedDict):
    total_value_in_usd: str
    r"""Total value of the portfolio in USD"""
    token_balances: List[TokenBalanceTypedDict]
    r"""List of token balances in the portfolio"""


class Portfolio(BaseModel):
    total_value_in_usd: str
    r"""Total value of the portfolio in USD"""

    token_balances: List[TokenBalance]
    r"""List of token balances in the portfolio"""
